######################################################################
######################################################################
################# General ############################################
######################################################################
######################################################################
GET http://192.168.5.34:3000/api

######################################################################
######################################################################
################# Login ##############################################
######################################################################
######################################################################

################# Login with id ################################
POST http://192.168.5.34:3000/api/login/67c93f408333cec4179f7904
Content-Type: application/json

{
    "password": "Fin345333!"
}

################# Login with username ################################
POST http://192.168.5.34:3000/api/login/
Content-Type: application/json

{
    "username": "test.usere.peter",
    "password": "Peter123!"
}

######################################################################
######################################################################
################# Profile ############################################
######################################################################
######################################################################

################# Get user profile ################################
GET http://192.168.5.34:3000/api/auth/profile/67a4408429308fd2840d377e

################# Update user profile ################################
POST http://192.168.5.34:3000/auth/profile/679b0811a48fe5e65be6f656
Content-Type: application/json

{
    "bio": "Im the best admin"
}

######################################################################
######################################################################
################# users CRUD #########################################
######################################################################
######################################################################

################# Create user ########################################
POST http://192.168.5.34:3000/api/request/users
content-type: application/json

{

  "fullName": "Fin The Human",
  "phoneNumber": "(619)969-6666",
  "email": "Fin.tester@potentiamaxima.com",
  "username": "Fin.tester",
  "password": "Fin3453333!",
  "role": "tester",
  "creationDate": "{{$timestamp}}",
  "activated": true,
  "currentLocation": "US",
  "bio": "Im the best test user"
}

################# Read all users ######################################
GET http://192.168.5.34:3000/api/request/users

################# Read a user by id ###################################
GET http://192.168.5.34:3000/api/request/users/67c93f408333cec4179f7904


################# Read a user by username #############################
GET http://192.168.5.34:3000/api/request/users/67c93f408333cec4179f7904

################# Update user data ###################################
PUT http://192.168.5.34:3000/api/request/users/67c93f408333cec4179f7904
content-type: application/json

{
  "fullName": "Mr Roboto Admin",
  "phoneNumber": "6199696660",
  "email": "test.user.Roboto@potentiamaxima.com",
  "password": "Roboto123!",
  "role": "tester",
  "creationDate": "{{$timestamp}}",
  "activated": true,
  "currentLocation": "US",
  "bio": "Im the best Roboto test user",
  "friends": ["67c93c4654dbccdef72e30d9","67c93c4654dbccdef72e30d9"]
}

################# Delete user ######################################
DELETE http://192.168.5.34:3000/api/request/users/67aee3321f2035e014397ba1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E2OGIzOGVjNjhlM2NkMjQ2MjQwOTAiLCJmdWxsTmFtZSI6InRlc3QgQWRtaW4iLCJwaG9uZU51bWJlciI6Iig2MTkpNjY2LTY2NjYiLCJlbWFpbCI6InRlc3QuYWRtaW5AcG90ZW50aWFtYXhpbWEuY29tIiwidXNlcm5hbWUiOiJ0ZXN0LmFkbWluIiwicm9sZSI6ImFkbWluIiwiY3JlYXRpb25EYXRlIjoiMTk3MC0wMS0yMVQwMzowMjo0Ny44NjRaIiwiYWN0aXZhdGVkIjp0cnVlLCJjdXJyZW50TG9jYXRpb24iOiJVUyIsImZyaWVuZHMiOltdLCJfX3YiOjAsImlhdCI6MTczOTQyNzYzMCwiZXhwIjoxNzM5NDMxMjMwfQ.S-n9PQUpADkJTaCJ4CRq9WCdjy195-paQ1Mahu9rQBo

######################################################################
######################################################################
################# scorecard CRUD #####################################
######################################################################
######################################################################

################# Create scorecard ###################################

POST http://192.168.5.34:3000/api/request/scorecards/user/create/683a4d2f98ee9699d6752a02
content-type: application/json

{
  "holeSelection": 9,
  "course": "Test Course 009",
  "date": "{{$Timestamp}}",
  "players": ["Fin.tester", "jesus.tester", "Roboto.tester", "john.tester"],
  "scores": 
  {
    "Roboto.tester": [4, 4, 4, 4, 4, 4, 4, 4, 4],
    "jesus.tester": [4, 4, 4, 4, 4, 4, 4, 4, 4],
    "peter.tester": [4, 4, 4, 4, 4, 4, 4, 4, 4],
    "john.tester": [4, 4, 4, 4, 4, 4, 4, 4, 4]
  }
}

################# Read all scorecards ################################
GET http://192.168.5.34:3000/api/request/scorecards

################# Read a scorecard by id ##############################
GET http://192.168.5.34:3000/api/request/scorecards/6835506a513308274da6b2d1

################# Read a scorecard by userid/username ################
GET http://192.168.5.34:3000/api/request/scorecards/user/67c92bfe82104d0c94b23a12

################# Update scorecard data ##############################
PUT http://192.168.5.34:3000/api/request/scorecards/user/update/6835506a513308274da6b2d1
content-type: application/json

{
  "scores": 
  {
    "peter.tester": [0, 0, 0, 0, 0, 0, 0, 0, 0]
  }
}

################# Delete scorecard ###################################
DELETE http://192.168.5.34:3000/api/request/scorecards/user/delete/6835506a513308274da6b2d1
Authorization
