######################################################################
######################################################################
################# General ############################################
######################################################################
######################################################################
GET http://localhost:3000/api

######################################################################
######################################################################
################# Login ##############################################
######################################################################
######################################################################

################# Login with id ################################
POST http://localhost:3000/api/login/67a2f66da4a135c87d1d926a
Content-Type: application/json

{
    "password": "admin"
}

################# Login with username ################################
POST http://localhost:3000/api/login/
Content-Type: application/json

{
    "username": "lbello.admin",
    "password": "admin"
}

######################################################################
######################################################################
################# Profile ############################################
######################################################################
######################################################################

################# Get user profile ################################
GET http://localhost:3000/api/auth/profile/679b0811a48fe5e65be6f656

################# Update user profile ################################
POST http://localhost:3000/auth/profile/679b0811a48fe5e65be6f656
Content-Type: application/json

{
    "bio": "Im the best admin"
}

######################################################################
######################################################################
################# users CRUD #########################################
######################################################################
######################################################################

################# Create user ########################################
POST http://localhost:3000/api/request/users
content-type: application/json

{
  "fullName": "Luis Admin",
  "phoneNumber": "(619)666-6666",
  "email": "lbello.admin@potentiamaxima.com",
  "username": "lbello.admin",
  "password": "admin",
  "role": "admin",
  "creationDate": "",
  "activated": true,
  "currentLocation": "US",
  "bio": "Im the best admin"
}

################# Read all users ######################################
GET http://localhost:3000/api/request/users

################# Read a user by id ###################################
GET http://localhost:3000/api/request/users/67a01e422043089f3458bba6

################# Update user data ###################################
PUT http://localhost:3000/api/request/users/67a01e422043089f3458bba6
content-type: application/json

{
  "fullName": "Mr Robo Admin",
  "username": "robo_01.admin",
  "password": "admin",
  "role": "robo admin",
  "creationDate": "",
  "activated": true,
  "currentLocation": "US",
  "phoneNumber": "(619)666-6666",
  "email": "robo_01admin@potentiamaxima.com"
}

################# Delete user ######################################
DELETE http://localhost:3000/api/request/users/6785a7d997c34bd5f5f1109d