######################################################################
######################################################################
################# General ############################################
######################################################################
######################################################################
GET http://localhost:3000/api

######################################################################
######################################################################
################# Login ##############################################
######################################################################
######################################################################

################# Login with id ################################
POST http://localhost:3000/api/login/67a2f66da4a135c87d1d926a
Content-Type: application/json

{
    "password": "admin"
}

################# Login with username ################################
POST http://localhost:3000/api/login/
Content-Type: application/json

{
    "username": "test.admin",
    "password": "admin"
}

######################################################################
######################################################################
################# Profile ############################################
######################################################################
######################################################################

################# Get user profile ################################
GET http://localhost:3000/api/auth/profile/67a4408429308fd2840d377e

################# Update user profile ################################
POST http://localhost:3000/auth/profile/679b0811a48fe5e65be6f656
Content-Type: application/json

{
    "bio": "Im the best admin"
}

######################################################################
######################################################################
################# users CRUD #########################################
######################################################################
######################################################################

################# Create user ########################################
POST http://localhost:3000/api/request/users
content-type: application/json

{
  "fullName": "Peter Parker",
  "phoneNumber": "(619)969-6666",
  "email": "test.user.peter@potentiamaxima.com",
  "username": "test.usere.peter",
  "password": "Peter123!",
  "role": "tester",
  "creationDate": "{{$timestamp}}",
  "activated": true,
  "currentLocation": "US",
  "bio": "Im the best test user"
}

################# Read all users ######################################
GET http://localhost:3000/api/request/users

################# Read a user by id ###################################
GET http://localhost:3000/api/request/users/67a441bb04e739b09a7a54cf

################# Update user data ###################################
PUT http://localhost:3000/api/request/users/67aee4337a44f78d85aa8ed7
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E2OGIzOGVjNjhlM2NkMjQ2MjQwOTAiLCJmdWxsTmFtZSI6InRlc3QgQWRtaW4iLCJwaG9uZU51bWJlciI6Iig2MTkpNjY2LTY2NjYiLCJlbWFpbCI6InRlc3QuYWRtaW5AcG90ZW50aWFtYXhpbWEuY29tIiwidXNlcm5hbWUiOiJ0ZXN0LmFkbWluIiwicm9sZSI6ImFkbWluIiwiY3JlYXRpb25EYXRlIjoiMTk3MC0wMS0yMVQwMzowMjo0Ny44NjRaIiwiYWN0aXZhdGVkIjp0cnVlLCJjdXJyZW50TG9jYXRpb24iOiJVUyIsImZyaWVuZHMiOltdLCJfX3YiOjAsImlhdCI6MTczOTQyNzYzMCwiZXhwIjoxNzM5NDMxMjMwfQ.S-n9PQUpADkJTaCJ4CRq9WCdjy195-paQ1Mahu9rQBo

{
  "fullName": "Mr Robo Admin",
  "username": "robo_01.admin",
  "password": "Admin01@01",
  "role": "admin",
  "creationDate": "",
  "activated": true,
  "currentLocation": "US",
  "phoneNumber": "(619)666-6666",
  "email": "robo_01admin@potentiamaxima.com"
}

################# Delete user ######################################
DELETE http://localhost:3000/api/request/users/67a4408429308fd2840d377e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2E2OGIzOGVjNjhlM2NkMjQ2MjQwOTAiLCJmdWxsTmFtZSI6InRlc3QgQWRtaW4iLCJwaG9uZU51bWJlciI6Iig2MTkpNjY2LTY2NjYiLCJlbWFpbCI6InRlc3QuYWRtaW5AcG90ZW50aWFtYXhpbWEuY29tIiwidXNlcm5hbWUiOiJ0ZXN0LmFkbWluIiwicm9sZSI6ImFkbWluIiwiY3JlYXRpb25EYXRlIjoiMTk3MC0wMS0yMVQwMzowMjo0Ny44NjRaIiwiYWN0aXZhdGVkIjp0cnVlLCJjdXJyZW50TG9jYXRpb24iOiJVUyIsImZyaWVuZHMiOltdLCJfX3YiOjAsImlhdCI6MTczOTQyNzYzMCwiZXhwIjoxNzM5NDMxMjMwfQ.S-n9PQUpADkJTaCJ4CRq9WCdjy195-paQ1Mahu9rQBo

######################################################################
######################################################################
################# scorecard CRUD #####################################
######################################################################
######################################################################

################# Create scorecard ###################################
POST http://localhost:3000/api/request/scorecards/user/create/67aee4337a44f78d85aa8ed7
content-type: application/json

{
  "holeSelection": 9,
  "course": "Test Course",
  "date": "{{$timestamp}}",
  "players": ["player1", "player2", "player3", "player4"],
  "scores": {
    "player1": {
      "hole1": 4,
      "hole2": 4,
      "hole3": 4,
      "hole4": 4,
      "hole5": 4,
      "hole6": 4,
      "hole7": 4,
      "hole8": 4,
      "hole9": 4
    },
    "player2": {
      "hole1": 4,
      "hole2": 4,
      "hole3": 4,
      "hole4": 4,
      "hole5": 4,
      "hole6": 4,
      "hole7": 4,
      "hole8": 4,
      "hole9": 4
    },
    "player3": {
      "hole1": 4,
      "hole2": 4,
      "hole3": 4,
      "hole4": 4,
      "hole5": 4,
      "hole6": 4,
      "hole7": 4,
      "hole8": 4,
      "hole9": 4
    },
    "player4": {
      "hole1": 4,
      "hole2": 4,
      "hole3": 4,
      "hole4": 4,
      "hole5": 4,
      "hole6": 4,
      "hole7": 4,
      "hole8": 4,
      "hole9": 4
    }
  }
}

################# Read all scorecards ################################
GET http://localhost:3000/api/request/scorecards

################# Read a scorecard by id ##############################
GET http://localhost:3000/api/request/scorecards/user/67a441bb04e739b09a7a54cf

################# Update scorecard data ##############################
PUT http://localhost:3000/api/request/scorecards/user/update/67a441bb04e739b09a7a54cf
content-type: application/json
Authorization

{
  "title": "Test Scorecard",
  "description": "This is a test scorecard",
  "creationDate": "{{$timestamp}}",
  "lastUpdate": "{{$timestamp}}",
  "status": "active",
  "owner": "67a4408429308fd2840d377e",
  "scorecardType": "test",
  "scorecardCategory": "test",
  "scorecardSubCategory": "test",
  "scorecardTags": ["test", "test", "test"],
  "scorecardData": {
    "test": "test"
  }
}

################# Delete scorecard ###################################
DELETE http://localhost:3000/api/request/scorecards/user/delete/67aee4337a44f78d85aa8ed7
Authorization
