GET http://localhost:3000/api

###
Get http://localhost:3000/status

###
POST http://localhost:3000/api/request/users
content-type: application/json

{
  "fullName": "testie",
  "username": "testietee",
  "password": "peepee",
  "role": "tester",
  "creationDate": "Mon, 13 Jan 2025 23:55:17 GMT",
  "activated": true,
  "currentLocation": "US",
  "phoneNumber": "(619)666-6666",
  "email": "testie@gmail.com"
}

###
GET http://localhost:3000/api/request/users

### 
GET http://localhost:3000/api/request/users/6785a7d997c34bd5f5f1109d

###
PUT http://localhost:3000/api/request/users/6785a7d997c34bd5f5f1109d
content-type: application/json

{
  "name": "luis-admin",
  "username": "luis_admin_01",
  "role": "admin"
}

### 
DELETE http://localhost:3000/api/request/users/6785a7d997c34bd5f5f1109d